language: python
python:
    - 3.5
    - 3.6

env:
    - NSQ_DOWNLOAD=nsq-1.0.0-compat.linux-amd64.go1.8

install:
    - sudo apt-get install libsnappy-dev
    - pip install python-snappy
    - wget https://s3.amazonaws.com/bitly-downloads/nsq/$NSQ_DOWNLOAD.tar.gz
    - tar zxvf $NSQ_DOWNLOAD.tar.gz
    - sudo cp $NSQ_DOWNLOAD/bin/nsqd $NSQ_DOWNLOAD/bin/nsqlookupd /usr/local/bin

    # - pip install pyflakes
    # - pip install pep8
    - pip install -e .

script:
    # - pyflakes asyncnsq tests
    # - pep8 asyncnsq tests
    - python runtests.py -v
