NEWLINE = b'\n'
DATA_SIZE = 4
FRAME_SIZE = 4
HEADER_SIZE = DATA_SIZE + FRAME_SIZE
MAX_CHUNK_SIZE = 65536

TIMESTAMP_SIZE = 8
ATTEMPTS_SIZE = 2
MSG_ID_SIZE = 16
MSG_HEADER = TIMESTAMP_SIZE + ATTEMPTS_SIZE + MSG_ID_SIZE

FRAME_TYPE_RESPONSE = 0
FRAME_TYPE_ERROR = 1
FRAME_TYPE_MESSAGE = 2
MAGIC_V2 = b'  V2'

NOP = b'NOP'
OK = b'OK'

HEARTBEAT = b'_heartbeat_'
BIN_OK = b'\x00\x00\x00\x06\x00\x00\x00\x00' + OK

# nsq TCP commands
AUTH = b'AUTH'
CLS = b'CLS'
DPUB = b'DPUB'
FIN = b'FIN'
IDENTIFY = b'IDENTIFY'
MPUB = b'MPUB'
PUB = b'PUB'
RDY = b'RDY'
REQ = b'REQ'
SUB = b'SUB'
TOUCH = b'TOUCH'

# connection status
INIT = 0
CONNECTED = 1

# NSQ defaults
DEFAULT_HOST = '127.0.0.1'

DEFAULT_NSQD_PORT_TCP = 4150
DEFAULT_NSQD_PORT_HTTP = 4151
DEFAULT_NSQD_PORT_HTTPS = 4152

DEFAULT_NSQLOOKUPD_PORT_TCP = 4160
DEFAULT_NSQLOOKUPD_PORT_HTTP = 4161
